version: "3.8"

services:
  mysql:
    image: mysql:8
    volumes:
      - ./data/:/var/lib/mysql
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: ObjectiveTest
    ports:
      - "3306:3306"