name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: production
    steps:
    
    - name: check files before checkout 
      run: pwd

    
    
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: ls && docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: log in to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

      
      
    
