name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
  
    
    steps:
    - name: check files before checkout 
      run: ls
    
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: ls && docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    
